// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/immutable/*",
    "/_app/version.json",
    "/favicon.png",
    "/logo.png",
    "/styles/bg.png",
    "/styles/bg.webp",
    "/styles/global.css",
    "/styles/reset.css",
    "/styles/text-mask-des.png",
    "/styles/text-mask-des.webp",
    "/styles/text-mask-dev.png",
    "/styles/text-mask-dev.webp",
    "/",
    "/about",
    "/contact",
    "/ischool-peer-feedback-tool",
    "/mission-threads",
    "/rochester-greenovation",
    "/sbc4e-hub",
    "/second-desk",
    "/web-design"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "C:\\Users\\Second Desk\\Documents\\Dev\\portfolio\\app\\.wrangler\\tmp\\pages-DYjbRk\\bundledWorker-0.29233224759237353.mjs";
import { isRoutingRuleMatch } from "C:\\Users\\Second Desk\\Documents\\Dev\\portfolio\\app\\node_modules\\wrangler\\templates\\pages-dev-util.ts";
export * from "C:\\Users\\Second Desk\\Documents\\Dev\\portfolio\\app\\.wrangler\\tmp\\pages-DYjbRk\\bundledWorker-0.29233224759237353.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=xneasg4ht4o.js.map
